### ISSUE TITLE
Missing Inversion

### ISSUE THREAD

**Issue by Bedlesssgod** [Blue-Nova/Floor-Is-Lava#3]
The isOwner Line needs to be inverted
https://github.com/Blue-Nova/Floor-Is-Lava/blob/73b902344313611bb35aca88cd2315303195bfa5/src/main/java/floorIsLava/command/MainCommand.java#L76C1-L76C1

**Comment by Blue-Nova** [comment]
I do not understand why it needs to be inverted.

**Comment by Blue-Nova** [comment]
Closed due to inactivity
